[toolchain]
anchor_version = "0.32.1"
solana_version = "1.18.0"

[features]
resolution = true
skip-lint = false

[programs.localnet]
darkpool = "7W5G8fa8QUBgrHFSfzMoCwoDhVzGM3ap4NWuQg4zpv6D"

[programs.devnet]
darkpool = "7W5G8fa8QUBgrHFSfzMoCwoDhVzGM3ap4NWuQg4zpv6D"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
build = "anchor build"
test = "anchor test --skip-local-validator"

