[workspace]
members = [
    "programs/darkpool",
    "encrypted-ixs",
]
resolver = "2"

[workspace.dependencies]
anchor-lang = "0.32.1"
anchor-spl = "0.32.1"

[profile.release]
overflow-checks = true

